### ISSUE TITLE
error when trying to convert midi

### ISSUE THREAD

**Issue by Sighfour** [KeppySoftware/KMC#69]
==== Start of Keppy's MIDI Converter Error ====
BASSException: BASS_ERROR_NOTAVAIL

BASSException: BASS Error: BASS_ERROR_NOTAVAIL

Calling method: BASSTempoAndFilter (Void BASSTempoAndFilter())
   at KeppyMIDIConverter.BASSControl.BASSCheckError() in E:\GitHub\KMC\KeppyMIDIConverter\Functions\BASSControl.cs:line 132
   at KeppyMIDIConverter.BASSControl.BASSTempoAndFilter() in E:\GitHub\KMC\KeppyMIDIConverter\Functions\BASSControl.cs:line 659
   at KeppyMIDIConverter.BASSControl.BASSStreamSystemRT(String str, Boolean PreviewMode) in E:\GitHub\KMC\KeppyMIDIConverter\Functions\BASSControl.cs:line 622
====  End of Keppy's MIDI Converter Error  ====

how do i fix this

**Comment by wwwwe-qm** [comment]
Restart KMC. If that doesnt work, restart your computer/laptop. Works to me
